baseurl = "http://bmintz.github.io/"
languageCode = "en-us"
title = "Ben Mintz's Blog"
disqusShortname = "benmintz-blog"
theme = "angels-ladder"

[permalinks]
post = "/:year/:month/:title/"

[indexes]
category = "categories"
tag = "tags"
page = "page"

[Params]
twitter = "https://twitter.com/benjaminmintz"
github = "https://github.com/bmintz"
copyright = 'This site is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License.'

